export const kitSeason = "2025/26" as const;

export type KitVariant = "home" | "away" | "third" | "retro";

export type KitSpec = {
  teamId: string;
  team: string;
  season: string;
  variant: KitVariant;
  manufacturer: string;
  mainSponsor: string;
  sleeveSponsor?: string;
  baseColor: string;
  accentColors: string[];
  pattern: string;
  collar: string;
  cuffs: string;
  crestPlacement: string;
  sponsorPlacement: string;
  shorts: string;
  socks: string;
  referenceImageUrl?: string;
  sourceUrls: string[];
  confidence: "high" | "medium" | "low";
};

export const kitVariants: Array<{ id: KitVariant; label: string; emoji: string }> = [
  { id: "home", label: "Home",  emoji: "🏠" },
  { id: "away", label: "Away",  emoji: "✈️" },
  { id: "third", label: "Third", emoji: "⚡" },
  { id: "retro", label: "Retro", emoji: "📼" },
];

const kitSpecs: KitSpec[] = [
  {
    teamId: "arsenal",
    team: "Arsenal",
    season: kitSeason,
    variant: "home",
    manufacturer: "adidas",
    mainSponsor: "Emirates",
    sleeveSponsor: undefined,
    baseColor: "red body with white sleeves",
    accentColors: ["white"],
    pattern: "contrasting-sleeve home shirt with a red main body and white sleeves",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/arsenal/home.jpg",
    sourceUrls: [
      "https://www.footballkitarchive.com/arsenal-fc-2025-26-home-kit-362997/"
    ],
    confidence: "low"
  },
  {
    teamId: "aston-villa",
    team: "Aston Villa",
    season: kitSeason,
    variant: "home",
    manufacturer: "adidas",
    mainSponsor: "Betano",
    sleeveSponsor: undefined,
    baseColor: "claret body with sky blue sleeves",
    accentColors: ["sky blue", "gold"],
    pattern: "contrasting-sleeve home shirt with burgundy main color and blue and gold details",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/aston-villa/home.jpg",
    sourceUrls: [
      "https://www.footballkitarchive.com/aston-villa-2025-26-home-kit-375022/"
    ],
    confidence: "low"
  },
  {
    teamId: "bournemouth",
    team: "AFC Bournemouth",
    season: kitSeason,
    variant: "home",
    manufacturer: "Umbro",
    mainSponsor: "bj88",
    sleeveSponsor: undefined,
    baseColor: "red and black vertical stripes",
    accentColors: ["black", "gold"],
    pattern: "red and black striped home shirt with rippled sand pattern inside the red stripes",
    collar: "collar with gold trim",
    cuffs: "sleeves with gold trim",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "black shorts",
    socks: "black socks",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/bournemouth/home.jpg",
    sourceUrls: [
      "https://www.footballkitarchive.com/afc-bournemouth-2025-26-home-kit-389299/"
    ],
    confidence: "low"
  },
  {
    teamId: "brentford",
    team: "Brentford",
    season: kitSeason,
    variant: "home",
    manufacturer: "Joma",
    mainSponsor: "Hollywoodbets",
    sleeveSponsor: undefined,
    baseColor: "red and white vertical stripes",
    accentColors: ["black", "white"],
    pattern: "wide red and white vertical stripes with tonal pinstriping in the red areas",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/brentford/home.jpg",
    sourceUrls: [
      "https://www.footballkitarchive.com/brentford-fc-2025-26-home-kit-384099/"
    ],
    confidence: "low"
  },
  {
    teamId: "brighton",
    team: "Brighton & Hove Albion",
    season: kitSeason,
    variant: "home",
    manufacturer: "Nike",
    mainSponsor: "American Express",
    sleeveSponsor: undefined,
    baseColor: "blue and white stripes",
    accentColors: ["blue", "white", "hyper turq"],
    pattern: "bold blue and white stripes either side of a central blue panel with mostly white reverse",
    collar: "unknown",
    cuffs: "blue sleeves edged with white cuffs",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/brighton/home.jpg",
    sourceUrls: [
      "https://www.footballkitarchive.com/brighton-hove-albion-2025-26-home-kit-384793/"
    ],
    confidence: "low"
  },
  {
    teamId: "burnley",
    team: "Burnley",
    season: kitSeason,
    variant: "home",
    manufacturer: "Castore",
    mainSponsor: "96",
    sleeveSponsor: undefined,
    baseColor: "claret",
    accentColors: ["sky blue", "white"],
    pattern: "claret home shirt with topographical contour-line graphic inspired by Lancashire hills",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/burnley/home.jpg",
    sourceUrls: [
      "https://www.footballkitarchive.com/burnley-fc-2025-26-home-kit-384949/"
    ],
    confidence: "low"
  },
  {
    teamId: "chelsea",
    team: "Chelsea",
    season: kitSeason,
    variant: "home",
    manufacturer: "Nike",
    mainSponsor: "unknown",
    sleeveSponsor: undefined,
    baseColor: "blue",
    accentColors: ["white", "red"],
    pattern: "traditional blue home shirt with grunge graphic detailing",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/chelsea/home.jpg",
    sourceUrls: [
      "https://www.footballkitarchive.com/chelsea-fc-2025-26-home-kit-402045/"
    ],
    confidence: "low"
  },
  {
    teamId: "crystal-palace",
    team: "Crystal Palace",
    season: kitSeason,
    variant: "home",
    manufacturer: "Macron",
    mainSponsor: "NET88",
    sleeveSponsor: undefined,
    baseColor: "red and royal blue vertical stripes",
    accentColors: ["royal blue", "white"],
    pattern: "bold red and royal blue vertical stripes separated by thin white pinstripes",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/crystal-palace/home.jpg",
    sourceUrls: [
      "https://www.footballkitarchive.com/crystal-palace-2025-26-home-kit-387542/"
    ],
    confidence: "low"
  },
  {
    teamId: "everton",
    team: "Everton",
    season: kitSeason,
    variant: "home",
    manufacturer: "Castore",
    mainSponsor: "Stake",
    sleeveSponsor: undefined,
    baseColor: "royal blue",
    accentColors: ["navy", "white"],
    pattern: "royal blue home shirt with subtle tonal horizontal wavy line pattern",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/everton/home.jpg",
    sourceUrls: [
      "https://www.footballkitarchive.com/everton-fc-2025-26-home-kit-370187/"
    ],
    confidence: "low"
  },
  {
    teamId: "fulham",
    team: "Fulham",
    season: kitSeason,
    variant: "home",
    manufacturer: "adidas",
    mainSponsor: "SBOBet",
    sleeveSponsor: undefined,
    baseColor: "white",
    accentColors: ["black"],
    pattern: "all-white home shirt with Craven Cottage balcony ironwork woven into the fabric",
    collar: "white neck with black accents",
    cuffs: "white cuffs with black accents",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "white shorts with black piping",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/fulham/home.jpg",
    sourceUrls: [
      "https://www.footballkitarchive.com/fulham-fc-2025-26-home-kit-393305/"
    ],
    confidence: "low"
  },
  {
    teamId: "leeds",
    team: "Leeds United",
    season: kitSeason,
    variant: "home",
    manufacturer: "adidas",
    mainSponsor: "Red Bull",
    sleeveSponsor: undefined,
    baseColor: "white",
    accentColors: ["blue", "yellow"],
    pattern: "plain white home shirt with blue adidas shoulder stripes",
    collar: "collar with unique blue and yellow pattern",
    cuffs: "sleeve cuffs with unique blue and yellow pattern",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/leeds/home.jpg",
    sourceUrls: [
      "https://www.footballkitarchive.com/leeds-united-2025-26-home-kit-384063/"
    ],
    confidence: "low"
  },
  {
    teamId: "liverpool",
    team: "Liverpool",
    season: kitSeason,
    variant: "home",
    manufacturer: "adidas",
    mainSponsor: "Standard Chartered",
    sleeveSponsor: undefined,
    baseColor: "strawberry red",
    accentColors: ["white"],
    pattern: "plain red home shirt with white logos",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/liverpool/home.jpg",
    sourceUrls: [
      "https://www.footballkitarchive.com/liverpool-fc-2025-26-home-kit-329216/"
    ],
    confidence: "low"
  },
  {
    teamId: "man-city",
    team: "Manchester City",
    season: kitSeason,
    variant: "home",
    manufacturer: "Puma",
    mainSponsor: "Etihad Airways",
    sleeveSponsor: undefined,
    baseColor: "sky blue",
    accentColors: ["white", "black"],
    pattern: "sky blue home shirt with sash design and white accents",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/man-city/home.jpg",
    sourceUrls: [
      "https://www.footballkitarchive.com/manchester-city-2025-26-home-kit-349847/"
    ],
    confidence: "low"
  },
  {
    teamId: "man-united",
    team: "Manchester United",
    season: kitSeason,
    variant: "home",
    manufacturer: "adidas",
    mainSponsor: "Snapdragon",
    sleeveSponsor: undefined,
    baseColor: "red",
    accentColors: ["black", "white"],
    pattern: "red graphic home shirt with white logos",
    collar: "black collar with white trim",
    cuffs: "black sleeve cuffs with white trim",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/man-united/home.jpg",
    sourceUrls: [
      "https://www.footballkitarchive.com/manchester-united-2025-26-home-kit-365645/"
    ],
    confidence: "low"
  },
  {
    teamId: "newcastle",
    team: "Newcastle United",
    season: kitSeason,
    variant: "home",
    manufacturer: "adidas",
    mainSponsor: "Sela",
    sleeveSponsor: undefined,
    baseColor: "black and white stripes",
    accentColors: ["sky blue"],
    pattern: "black and white stripes with serrated Shepherd's Check edges",
    collar: "collar with light blue piping",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/newcastle/home.jpg",
    sourceUrls: [
      "https://www.footballkitarchive.com/newcastle-united-2025-26-home-kit-370607/"
    ],
    confidence: "low"
  },
  {
    teamId: "nottingham-forest",
    team: "Nottingham Forest",
    season: kitSeason,
    variant: "home",
    manufacturer: "adidas",
    mainSponsor: "Bally's",
    sleeveSponsor: "Ideagen",
    baseColor: "bright Nottingham Forest red",
    accentColors: ["white", "dark red"],
    pattern: "thin vertical white pinstripes with additional subtle dark red pinstripes on the red shirt base",
    collar: "red polo collar with white trim and a single-button placket",
    cuffs: "red sleeve cuffs with a narrow white horizontal trim stripe",
    crestPlacement: "Nottingham Forest crest inside a white shield on the wearer's left chest, with two stars above",
    sponsorPlacement: "white Bally's script sponsor large across the centre chest",
    shorts: "white shorts with red adidas detailing",
    socks: "red socks with white adidas striping",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/nottingham-forest/home.jpg",
    sourceUrls: [
      "https://www.footballkitarchive.com/nottingham-forest-2025-26-home-kit-397475/",
      "https://www.premierleague.com/en/news/4353461",
      "https://www.premierleague.com/news/4352974"
    ],
    confidence: "high"
  },
  {
    teamId: "sunderland",
    team: "Sunderland",
    season: kitSeason,
    variant: "home",
    manufacturer: "Hummel",
    mainSponsor: "W88",
    sleeveSponsor: undefined,
    baseColor: "red and white vertical stripes",
    accentColors: ["black"],
    pattern: "red and white vertical stripes with segmented red stripe detailing",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/sunderland/home.jpg",
    sourceUrls: [
      "https://www.footballkitarchive.com/sunderland-afc-2025-26-home-kit-376009/"
    ],
    confidence: "low"
  },
  {
    teamId: "tottenham",
    team: "Tottenham Hotspur",
    season: kitSeason,
    variant: "home",
    manufacturer: "Nike",
    mainSponsor: "AIA",
    sleeveSponsor: undefined,
    baseColor: "white",
    accentColors: ["navy"],
    pattern: "predominantly white home shirt with contrasting sleeve design",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/tottenham/home.jpg",
    sourceUrls: [
      "https://www.footballkitarchive.com/tottenham-hotspur-2025-26-home-kit-329780/"
    ],
    confidence: "low"
  },
  {
    teamId: "west-ham",
    team: "West Ham United",
    season: kitSeason,
    variant: "home",
    manufacturer: "Umbro",
    mainSponsor: "Boylesports",
    sleeveSponsor: undefined,
    baseColor: "claret",
    accentColors: ["sky blue", "white"],
    pattern: "minimal all-claret home shirt with tonal blue underarm inserts",
    collar: "ribbed collar with alternating claret and blue stripes",
    cuffs: "ribbed sleeve cuffs with alternating claret and blue stripes",
    crestPlacement: "full-color club crest on the front",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/west-ham/home.jpg",
    sourceUrls: [
      "https://www.footballkitarchive.com/west-ham-united-2025-26-home-kit-385259/"
    ],
    confidence: "low"
  },
  {
    teamId: "wolves",
    team: "Wolverhampton Wanderers",
    season: kitSeason,
    variant: "home",
    manufacturer: "Sudu",
    mainSponsor: "DEBET",
    sleeveSponsor: undefined,
    baseColor: "gold",
    accentColors: ["black"],
    pattern: "gold home shirt with subtle print inspired by Molineux Pleasure Grounds",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/wolves/home.jpg",
    sourceUrls: [
      "https://www.footballkitarchive.com/wolverhampton-wanderers-2025-26-home-kit-365548/"
    ],
    confidence: "low"
  }
];

const fallbackKitSpecs: KitSpec[] = [
  // Away kits — images hosted in Supabase kit-images bucket
  {
    teamId: "arsenal",
    team: "Arsenal",
    season: kitSeason,
    variant: "away",
    manufacturer: "adidas",
    mainSponsor: "Emirates",
    baseColor: "navy",
    accentColors: ["red", "royal blue"],
    pattern: "bold lightning bolt graphic pattern in royal blue over a navy base",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/arsenal/away.jpg",
    sourceUrls: ["https://www.footballkitarchive.com/arsenal-fc-2025-26-away-kit-374085/"],
    confidence: "medium"
  },
  {
    teamId: "aston-villa",
    team: "Aston Villa",
    season: kitSeason,
    variant: "away",
    manufacturer: "adidas",
    mainSponsor: "Betano",
    baseColor: "black",
    accentColors: ["sky blue", "silver"],
    pattern: "sleek all-black design with monochrome silver and grey logos and crest",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/aston-villa/away.jpg",
    sourceUrls: ["https://www.footballkitarchive.com/aston-villa-2025-26-away-kit-374086/"],
    confidence: "medium"
  },
  {
    teamId: "bournemouth",
    team: "AFC Bournemouth",
    season: kitSeason,
    variant: "away",
    manufacturer: "Umbro",
    mainSponsor: "bj88",
    baseColor: "blue and black vertical stripes",
    accentColors: ["black"],
    pattern: "throwback blue and black vertical stripe design",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/bournemouth/away.jpg",
    sourceUrls: ["https://www.footballkitarchive.com/afc-bournemouth-2025-26-away-kit-395235/"],
    confidence: "medium"
  },
  {
    teamId: "brentford",
    team: "Brentford",
    season: kitSeason,
    variant: "away",
    manufacturer: "Joma",
    mainSponsor: "Hollywoodbets",
    baseColor: "brown",
    accentColors: ["gold"],
    pattern: "brown base with gold graphic pattern detailing",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/brentford/away.jpg",
    sourceUrls: ["https://www.footballkitarchive.com/brentford-fc-2025-26-away-kit-393257/"],
    confidence: "medium"
  },
  {
    teamId: "brighton",
    team: "Brighton & Hove Albion",
    season: kitSeason,
    variant: "away",
    manufacturer: "Nike",
    mainSponsor: "American Express",
    baseColor: "purple",
    accentColors: ["purple"],
    pattern: "all-purple shirt with tonal sash stripe detail",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/brighton/away.jpg",
    sourceUrls: ["https://www.footballkitarchive.com/brighton-hove-albion-2025-26-away-kit-384942/"],
    confidence: "medium"
  },
  {
    teamId: "burnley",
    team: "Burnley",
    season: kitSeason,
    variant: "away",
    manufacturer: "Castore",
    mainSponsor: "96",
    baseColor: "sky blue",
    accentColors: ["claret", "white"],
    pattern: "sky blue base with claret and white graphic detailing",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/burnley/away.jpg",
    sourceUrls: ["https://www.footballkitarchive.com/burnley-fc-2025-26-away-kit-395926/"],
    confidence: "medium"
  },
  {
    teamId: "chelsea",
    team: "Chelsea",
    season: kitSeason,
    variant: "away",
    manufacturer: "Nike",
    mainSponsor: "unknown",
    baseColor: "off-white",
    accentColors: ["green", "red"],
    pattern: "off-white base with green and red stripe accents",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/chelsea/away.jpg",
    sourceUrls: ["https://www.footballkitarchive.com/chelsea-fc-2025-26-away-kit-347356/"],
    confidence: "medium"
  },
  {
    teamId: "crystal-palace",
    team: "Crystal Palace",
    season: kitSeason,
    variant: "away",
    manufacturer: "Macron",
    mainSponsor: "NET88",
    baseColor: "white",
    accentColors: ["red", "blue"],
    pattern: "white shirt with red and blue single stripe detail",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/crystal-palace/away.jpg",
    sourceUrls: ["https://www.footballkitarchive.com/crystal-palace-2025-26-away-kit-402008/"],
    confidence: "medium"
  },
  {
    teamId: "everton",
    team: "Everton",
    season: kitSeason,
    variant: "away",
    manufacturer: "Castore",
    mainSponsor: "Stake",
    baseColor: "yellow",
    accentColors: ["black"],
    pattern: "yellow base with black graphic detailing",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/everton/away.jpg",
    sourceUrls: ["https://www.footballkitarchive.com/everton-fc-2025-26-away-kit-377338/"],
    confidence: "medium"
  },
  {
    teamId: "fulham",
    team: "Fulham",
    season: kitSeason,
    variant: "away",
    manufacturer: "adidas",
    mainSponsor: "SBOBet",
    baseColor: "green",
    accentColors: ["navy", "white"],
    pattern: "green base with navy and white trim",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/fulham/away.jpg",
    sourceUrls: ["https://www.footballkitarchive.com/fulham-fc-2025-26-away-kit-395935/"],
    confidence: "medium"
  },
  {
    teamId: "leeds",
    team: "Leeds United",
    season: kitSeason,
    variant: "away",
    manufacturer: "adidas",
    mainSponsor: "Red Bull",
    baseColor: "blue",
    accentColors: ["yellow", "white"],
    pattern: "blue and yellow/white hoop pattern",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/leeds/away.jpg",
    sourceUrls: ["https://www.footballkitarchive.com/leeds-united-2025-26-away-kit-389188/"],
    confidence: "medium"
  },
  {
    teamId: "liverpool",
    team: "Liverpool",
    season: kitSeason,
    variant: "away",
    manufacturer: "adidas",
    mainSponsor: "Standard Chartered",
    baseColor: "off-white",
    accentColors: ["red", "black"],
    pattern: "clean off-white/cream base with red and black trim",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/liverpool/away.jpg",
    sourceUrls: ["https://www.footballkitarchive.com/liverpool-fc-2025-26-away-kit-374741/"],
    confidence: "medium"
  },
  {
    teamId: "man-city",
    team: "Manchester City",
    season: kitSeason,
    variant: "away",
    manufacturer: "Puma",
    mainSponsor: "Etihad Airways",
    baseColor: "black",
    accentColors: ["silver"],
    pattern: "all-black with silver accents and detailing",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/man-city/away.jpg",
    sourceUrls: ["https://www.footballkitarchive.com/manchester-city-2025-26-away-kit-362225/"],
    confidence: "medium"
  },
  {
    teamId: "man-united",
    team: "Manchester United",
    season: kitSeason,
    variant: "away",
    manufacturer: "adidas",
    mainSponsor: "Snapdragon",
    baseColor: "white",
    accentColors: ["purple"],
    pattern: "white base with purple graphic pattern and purple detailing",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/man-united/away.jpg",
    sourceUrls: ["https://www.footballkitarchive.com/manchester-united-2025-26-away-kit-334149/"],
    confidence: "medium"
  },
  {
    teamId: "newcastle",
    team: "Newcastle United",
    season: kitSeason,
    variant: "away",
    manufacturer: "adidas",
    mainSponsor: "Sela",
    baseColor: "green",
    accentColors: ["white"],
    pattern: "green base with white graphic detailing",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/newcastle/away.jpg",
    sourceUrls: ["https://www.footballkitarchive.com/newcastle-united-2025-26-away-kit-380305/"],
    confidence: "medium"
  },
  {
    teamId: "sunderland",
    team: "Sunderland",
    season: kitSeason,
    variant: "away",
    manufacturer: "Hummel",
    mainSponsor: "W88",
    baseColor: "blue",
    accentColors: ["white", "red"],
    pattern: "blue base with white and red graphic accents",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/sunderland/away.jpg",
    sourceUrls: ["https://www.footballkitarchive.com/sunderland-afc-2025-26-away-kit-375053/"],
    confidence: "medium"
  },
  {
    teamId: "tottenham",
    team: "Tottenham Hotspur",
    season: kitSeason,
    variant: "away",
    manufacturer: "Nike",
    mainSponsor: "AIA",
    baseColor: "black",
    accentColors: ["grey", "white"],
    pattern: "black and grey/white checker pattern",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/tottenham/away.jpg",
    sourceUrls: ["https://www.footballkitarchive.com/tottenham-hotspur-2025-26-away-kit-334139/"],
    confidence: "medium"
  },
  {
    teamId: "west-ham",
    team: "West Ham United",
    season: kitSeason,
    variant: "away",
    manufacturer: "Umbro",
    mainSponsor: "Boylesports",
    baseColor: "off-white",
    accentColors: ["navy", "claret"],
    pattern: "off-white/cream base with navy and claret trim",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/west-ham/away.jpg",
    sourceUrls: ["https://www.footballkitarchive.com/west-ham-united-2025-26-away-kit-389848/"],
    confidence: "medium"
  },
  {
    teamId: "wolves",
    team: "Wolverhampton Wanderers",
    season: kitSeason,
    variant: "away",
    manufacturer: "Sudu",
    mainSponsor: "DEBET",
    baseColor: "sky blue",
    accentColors: ["green"],
    pattern: "sky blue base with green graphic detailing",
    collar: "unknown",
    cuffs: "unknown",
    crestPlacement: "unknown",
    sponsorPlacement: "unknown",
    shorts: "unknown",
    socks: "unknown",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/wolves/away.jpg",
    sourceUrls: ["https://www.footballkitarchive.com/wolverhampton-wanderers-2025-26-away-kit-393140/"],
    confidence: "medium"
  },
  // Nottingham Forest (already existed)
  {
    teamId: "nottingham-forest",
    team: "Nottingham Forest",
    season: kitSeason,
    variant: "away",
    manufacturer: "adidas",
    mainSponsor: "Bally's",
    sleeveSponsor: "Ideagen",
    baseColor: "off-white",
    accentColors: ["dark navy", "light grey"],
    pattern: "subtle lace-inspired tonal graphic pattern across the shirt body",
    collar: "simple off-white crew collar",
    cuffs: "off-white sleeve cuffs with minimal dark navy detailing",
    crestPlacement: "dark navy Nottingham Forest crest on the wearer's left chest",
    sponsorPlacement: "dark navy Bally's script sponsor across the centre chest",
    shorts: "off-white shorts with dark navy adidas detailing",
    socks: "off-white socks with dark navy accents",
    referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/nottingham-forest/away.jpg",
    sourceUrls: [
      "https://www.footballkitarchive.com/nottingham-forest-2025-26-away-kit/357963/"
    ],
    confidence: "medium"
  },
  {
    teamId: "nottingham-forest",
    team: "Nottingham Forest",
    season: kitSeason,
    variant: "third",
    manufacturer: "adidas",
    mainSponsor: "Bally's",
    sleeveSponsor: "Ideagen",
    baseColor: "navy legend ink",
    accentColors: ["solar red", "dark navy"],
    pattern: "tonal navy graphic waves pattern across the front of the shirt",
    collar: "navy crew collar with bright solar red rear and shoulder accents",
    cuffs: "navy sleeve cuffs with solar red piping",
    crestPlacement: "solar red Nottingham Forest crest on the wearer's left chest, with two stars above",
    sponsorPlacement: "solar red Bally's script sponsor across the centre chest",
    shorts: "navy shorts with solar red adidas detailing",
    socks: "navy socks with solar red adidas striping",
    referenceImageUrl: "https://www.footballkitarchive.com/cdn/2025/08/29/N4FMH83z3OWAdP9/nottingham-forest-2025-26-third-kit.jpg",
    sourceUrls: [
      "https://www.footballkitarchive.com/nottingham-forest-2025-26-third-kit-405292/"
    ],
    confidence: "high"
  }
];

// ─── 2026 World Cup International Kit Specs ─────────────────────────────────
// Auto-generated by scratch/scrape_international_kits.ts
// Reference images sourced from Wikimedia Commons (freely licensed).
// Stored in Supabase: kit-images/international/<teamId>/home.<ext>
// 3 teams skipped (no images found): Sweden, Australia, New Zealand
export const internationalKitSpecs: KitSpec[] = [
  { teamId: "canada", team: "Canada", season: kitSeason, variant: "home", manufacturer: "unknown", mainSponsor: "unknown", baseColor: "red", accentColors: ["white"], pattern: "red home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/canada/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/FIFA_Women%27s_World_Cup_Canada_2015_-_Edmonton.jpg/1280px-FIFA_Women%27s_World_Cup_Canada_2015_-_Edmonton.jpg"], confidence: "low" },
  { teamId: "mexico", team: "Mexico", season: kitSeason, variant: "home", manufacturer: "unknown", mainSponsor: "unknown", baseColor: "green", accentColors: ["white", "red"], pattern: "green home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/mexico/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/FIFA_World_Cup_2010_France_Mexico.jpg/1280px-FIFA_World_Cup_2010_France_Mexico.jpg"], confidence: "low" },
  { teamId: "usa", team: "United States", season: kitSeason, variant: "home", manufacturer: "unknown", mainSponsor: "unknown", baseColor: "white", accentColors: ["blue", "red"], pattern: "white home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/usa/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/U.S._soccer_team%2C_1916.jpg/1280px-U.S._soccer_team%2C_1916.jpg"], confidence: "low" },
  { teamId: "england", team: "England", season: kitSeason, variant: "home", manufacturer: "Nike", mainSponsor: "none", baseColor: "white", accentColors: ["navy", "red"], pattern: "white home shirt with navy and red trim", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/england/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/England_team.jpg/500px-England_team.jpg"], confidence: "low" },
  { teamId: "france", team: "France", season: kitSeason, variant: "home", manufacturer: "Nike", mainSponsor: "none", baseColor: "royal blue", accentColors: ["white", "red"], pattern: "royal blue home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/france/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Zidane-France-2006-home-shirt.jpg/500px-Zidane-France-2006-home-shirt.jpg"], confidence: "low" },
  { teamId: "germany", team: "Germany", season: kitSeason, variant: "home", manufacturer: "adidas", mainSponsor: "none", baseColor: "white", accentColors: ["black", "red", "gold"], pattern: "white home shirt with tricolour V-design", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/germany/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/2022_FIFA_World_Cup_Germany_1%E2%80%932_Japan_-_Germany_lineup.jpg/500px-2022_FIFA_World_Cup_Germany_1%E2%80%932_Japan_-_Germany_lineup.jpg"], confidence: "low" },
  { teamId: "spain", team: "Spain", season: kitSeason, variant: "home", manufacturer: "adidas", mainSponsor: "none", baseColor: "red", accentColors: ["yellow", "navy"], pattern: "red home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/spain/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/2010_FIFA_World_Cup_Spain_with_cup.JPG/1280px-2010_FIFA_World_Cup_Spain_with_cup.JPG"], confidence: "low" },
  { teamId: "portugal", team: "Portugal", season: kitSeason, variant: "home", manufacturer: "Nike", mainSponsor: "none", baseColor: "red", accentColors: ["green", "gold"], pattern: "red home shirt with green sleeves", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/portugal/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Portugal_national_football_team_World_Cup_2018.jpg/1280px-Portugal_national_football_team_World_Cup_2018.jpg"], confidence: "low" },
  { teamId: "netherlands", team: "Netherlands", season: kitSeason, variant: "home", manufacturer: "Nike", mainSponsor: "none", baseColor: "orange", accentColors: ["white", "blue"], pattern: "orange home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/netherlands/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/FIFA_World_Cup_2010_Final_Netherlands_team.JPG/1280px-FIFA_World_Cup_2010_Final_Netherlands_team.JPG"], confidence: "low" },
  { teamId: "belgium", team: "Belgium", season: kitSeason, variant: "home", manufacturer: "adidas", mainSponsor: "none", baseColor: "red", accentColors: ["black", "yellow"], pattern: "red home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/belgium/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/The_Belgium_national_team_line-up_before_the_match_against_Brazil%2C_6_July_2018.jpg/1280px-The_Belgium_national_team_line-up_before_the_match_against_Brazil%2C_6_July_2018.jpg"], confidence: "low" },
  { teamId: "croatia", team: "Croatia", season: kitSeason, variant: "home", manufacturer: "Nike", mainSponsor: "none", baseColor: "red and white chequered", accentColors: ["white", "red"], pattern: "iconic red and white chequered home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/croatia/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Croatian_nation_football_squad_%2842545971655%29.jpg/1280px-Croatian_nation_football_squad_%2842545971655%29.jpg"], confidence: "low" },
  { teamId: "switzerland", team: "Switzerland", season: kitSeason, variant: "home", manufacturer: "Puma", mainSponsor: "none", baseColor: "red", accentColors: ["white"], pattern: "red home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/switzerland/home.png", sourceUrls: ["https://en.wikipedia.org/wiki/Switzerland_national_football_team"], confidence: "low" },
  { teamId: "austria", team: "Austria", season: kitSeason, variant: "home", manufacturer: "Puma", mainSponsor: "none", baseColor: "red", accentColors: ["white"], pattern: "red home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/austria/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/FIFA_WC-qualification_2014_-_Austria_vs._Germany_2012-09-11_%2801%29.jpg/1280px-FIFA_WC-qualification_2014_-_Austria_vs._Germany_2012-09-11_%2801%29.jpg"], confidence: "low" },
  { teamId: "norway", team: "Norway", season: kitSeason, variant: "home", manufacturer: "Nike", mainSponsor: "none", baseColor: "red", accentColors: ["white", "blue"], pattern: "red home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/norway/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Norway_2015.jpg/1280px-Norway_2015.jpg"], confidence: "low" },
  { teamId: "scotland", team: "Scotland", season: kitSeason, variant: "home", manufacturer: "adidas", mainSponsor: "none", baseColor: "dark blue", accentColors: ["white", "gold"], pattern: "dark navy blue home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/scotland/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/1872_engl_v_scotland_ralston.jpg/500px-1872_engl_v_scotland_ralston.jpg"], confidence: "low" },
  { teamId: "czech-republic", team: "Czech Republic", season: kitSeason, variant: "home", manufacturer: "Puma", mainSponsor: "none", baseColor: "red", accentColors: ["white", "blue"], pattern: "red home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/czech-republic/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Closeup_Czech_Republic_versus_Ghana_at_2006_World_Cup.jpg/1280px-Closeup_Czech_Republic_versus_Ghana_at_2006_World_Cup.jpg"], confidence: "low" },
  { teamId: "turkey", team: "Turkey", season: kitSeason, variant: "home", manufacturer: "Nike", mainSponsor: "none", baseColor: "red", accentColors: ["white"], pattern: "red home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/turkey/home.png", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Turkey_national_football_team_%2828.05.1950%29.png/500px-Turkey_national_football_team_%2828.05.1950%29.png"], confidence: "low" },
  { teamId: "bosnia", team: "Bosnia and Herzegovina", season: kitSeason, variant: "home", manufacturer: "Macron", mainSponsor: "none", baseColor: "dark blue", accentColors: ["yellow"], pattern: "dark blue home shirt with yellow diagonal stripe", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/bosnia/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/20150331_2028_AUT_BIH_2186.jpg/1280px-20150331_2028_AUT_BIH_2186.jpg"], confidence: "low" },
  { teamId: "brazil", team: "Brazil", season: kitSeason, variant: "home", manufacturer: "Nike", mainSponsor: "none", baseColor: "canary yellow", accentColors: ["green", "blue", "white"], pattern: "iconic canary yellow home shirt with green trim", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/brazil/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Brazil_1970.JPG/1280px-Brazil_1970.JPG"], confidence: "low" },
  { teamId: "argentina", team: "Argentina", season: kitSeason, variant: "home", manufacturer: "adidas", mainSponsor: "none", baseColor: "sky blue and white stripes", accentColors: ["white", "sky blue"], pattern: "iconic sky blue and white vertical stripe home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/argentina/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Argentina_equipo_v_combinadopaulista_1908.jpg/1280px-Argentina_equipo_v_combinadopaulista_1908.jpg"], confidence: "low" },
  { teamId: "colombia", team: "Colombia", season: kitSeason, variant: "home", manufacturer: "adidas", mainSponsor: "none", baseColor: "yellow", accentColors: ["blue", "red"], pattern: "yellow home shirt with blue trim", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/colombia/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Colombia_en_el_Sudamericano_1957%2C_Estadio%2C_1957-04-26_%28728%29.jpg/1280px-Colombia_en_el_Sudamericano_1957%2C_Estadio%2C_1957-04-26_%28728%29.jpg"], confidence: "low" },
  { teamId: "ecuador", team: "Ecuador", season: kitSeason, variant: "home", manufacturer: "Marathon", mainSponsor: "none", baseColor: "yellow", accentColors: ["blue", "red"], pattern: "yellow home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/ecuador/home.png", sourceUrls: ["https://upload.wikimedia.org/wikipedia/en/b/ba/Ecuador_national_football_team.png"], confidence: "low" },
  { teamId: "uruguay", team: "Uruguay", season: kitSeason, variant: "home", manufacturer: "Puma", mainSponsor: "none", baseColor: "sky blue", accentColors: ["white", "black"], pattern: "sky blue home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/uruguay/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/2018_FIFA_World_Cup_Group_A_march_Uruguay_vs_Russia_2018-06-25.jpg/1280px-2018_FIFA_World_Cup_Group_A_march_Uruguay_vs_Russia_2018-06-25.jpg"], confidence: "low" },
  { teamId: "paraguay", team: "Paraguay", season: kitSeason, variant: "home", manufacturer: "unknown", mainSponsor: "none", baseColor: "red and white stripes", accentColors: ["red", "white", "blue"], pattern: "red and white vertical stripe home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/paraguay/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Paraguay_1929.JPG/500px-Paraguay_1929.JPG"], confidence: "low" },
  { teamId: "morocco", team: "Morocco", season: kitSeason, variant: "home", manufacturer: "Puma", mainSponsor: "none", baseColor: "red", accentColors: ["green", "white"], pattern: "red home shirt with green trim", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/morocco/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Morocco_vs_Niger%2C_February_09_2014_%28cropped%29.jpg/1280px-Morocco_vs_Niger%2C_February_09_2014_%28cropped%29.jpg"], confidence: "low" },
  { teamId: "senegal", team: "Senegal", season: kitSeason, variant: "home", manufacturer: "Puma", mainSponsor: "none", baseColor: "white", accentColors: ["green", "yellow", "red"], pattern: "white home shirt with green and yellow trim", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/senegal/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/La_victoire_s%C3%A9n%C3%A9galaise.jpg/1280px-La_victoire_s%C3%A9n%C3%A9galaise.jpg"], confidence: "low" },
  { teamId: "nigeria", team: "Nigeria", season: kitSeason, variant: "home", manufacturer: "Nike", mainSponsor: "none", baseColor: "green", accentColors: ["white"], pattern: "green home shirt with white trim", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/nigeria/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Black_Stars_%28Ghana_national_football_team%29_Jersey_1970s%E2%80%941980s.jpg/1280px-Black_Stars_%28Ghana_national_football_team%29_Jersey_1970s%E2%80%941980s.jpg"], confidence: "low" },
  { teamId: "ivory-coast", team: "Ivory Coast", season: kitSeason, variant: "home", manufacturer: "Nike", mainSponsor: "none", baseColor: "orange", accentColors: ["white", "green"], pattern: "orange home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/ivory-coast/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cote_d%27Iviore_NT_2010.jpg/1280px-Cote_d%27Iviore_NT_2010.jpg"], confidence: "low" },
  { teamId: "egypt", team: "Egypt", season: kitSeason, variant: "home", manufacturer: "Puma", mainSponsor: "none", baseColor: "red", accentColors: ["white", "black"], pattern: "red home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/egypt/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/%C3%89quipe_d%27%C3%89gypte_de_football_1920.jpg/1280px-%C3%89quipe_d%27%C3%89gypte_de_football_1920.jpg"], confidence: "low" },
  { teamId: "ghana", team: "Ghana", season: kitSeason, variant: "home", manufacturer: "Puma", mainSponsor: "none", baseColor: "white", accentColors: ["gold", "green", "red", "black"], pattern: "white home shirt with gold trim", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/ghana/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Black_Stars_%28Ghana_national_football_team%29_Jersey_1970s%E2%80%941980s.jpg/1280px-Black_Stars_%28Ghana_national_football_team%29_Jersey_1970s%E2%80%941980s.jpg"], confidence: "low" },
  { teamId: "algeria", team: "Algeria", season: kitSeason, variant: "home", manufacturer: "Puma", mainSponsor: "none", baseColor: "white", accentColors: ["green", "red"], pattern: "white home shirt with green trim", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/algeria/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Algeria_NT_training_2013_AFCON.jpg/500px-Algeria_NT_training_2013_AFCON.jpg"], confidence: "low" },
  { teamId: "south-africa", team: "South Africa", season: kitSeason, variant: "home", manufacturer: "Nike", mainSponsor: "none", baseColor: "yellow", accentColors: ["green", "white", "gold"], pattern: "yellow Bafana Bafana home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/south-africa/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Bafana_joshua_smith.jpg/1280px-Bafana_joshua_smith.jpg"], confidence: "low" },
  { teamId: "dr-congo", team: "DR Congo", season: kitSeason, variant: "home", manufacturer: "unknown", mainSponsor: "none", baseColor: "blue", accentColors: ["yellow", "red"], pattern: "blue home shirt with yellow trim", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/dr-congo/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/CAN_2023RD_Congo_2-1_Guin%C3%A9e9968.jpg/1280px-CAN_2023RD_Congo_2-1_Guin%C3%A9e9968.jpg"], confidence: "low" },
  { teamId: "cape-verde", team: "Cape Verde", season: kitSeason, variant: "home", manufacturer: "unknown", mainSponsor: "none", baseColor: "blue", accentColors: ["white", "red"], pattern: "blue home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/cape-verde/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Ryan_Mendes_%28LOSC_Lille%29.JPG/1280px-Ryan_Mendes_%28LOSC_Lille%29.JPG"], confidence: "low" },
  { teamId: "tunisia", team: "Tunisia", season: kitSeason, variant: "home", manufacturer: "Kappa", mainSponsor: "none", baseColor: "white", accentColors: ["red"], pattern: "white home shirt with red trim", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/tunisia/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Tunisia_-_Netherlands_%28Stade_de_Rad%C3%A8s%29_3.jpg/1280px-Tunisia_-_Netherlands_%28Stade_de_Rad%C3%A8s%29_3.jpg"], confidence: "low" },
  { teamId: "japan", team: "Japan", season: kitSeason, variant: "home", manufacturer: "adidas", mainSponsor: "none", baseColor: "navy blue", accentColors: ["white", "red"], pattern: "navy blue Samurai Blue home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/japan/home.jpg", sourceUrls: ["https://en.wikipedia.org/wiki/Japan_national_football_team"], confidence: "low" },
  { teamId: "south-korea", team: "South Korea", season: kitSeason, variant: "home", manufacturer: "Nike", mainSponsor: "none", baseColor: "red", accentColors: ["white", "navy"], pattern: "red home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/south-korea/home.jpg", sourceUrls: ["https://en.wikipedia.org/wiki/South_Korea_national_football_team"], confidence: "low" },
  { teamId: "saudi-arabia", team: "Saudi Arabia", season: kitSeason, variant: "home", manufacturer: "adidas", mainSponsor: "none", baseColor: "white", accentColors: ["green"], pattern: "white home shirt with green trim", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/saudi-arabia/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Saudi_Arabia_national_football_team_in_1984.jpg/500px-Saudi_Arabia_national_football_team_in_1984.jpg"], confidence: "low" },
  { teamId: "iran", team: "Iran", season: kitSeason, variant: "home", manufacturer: "Meyba", mainSponsor: "none", baseColor: "white", accentColors: ["green", "red"], pattern: "white home shirt with green and red trim", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/iran/home.png", sourceUrls: ["https://en.wikipedia.org/wiki/Iran_national_football_team"], confidence: "low" },
  { teamId: "iraq", team: "Iraq", season: kitSeason, variant: "home", manufacturer: "unknown", mainSponsor: "none", baseColor: "green", accentColors: ["white", "red", "black"], pattern: "green home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/iraq/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Iraq_national_football_team_2011.jpg/1280px-Iraq_national_football_team_2011.jpg"], confidence: "low" },
  { teamId: "qatar", team: "Qatar", season: kitSeason, variant: "home", manufacturer: "adidas", mainSponsor: "none", baseColor: "maroon", accentColors: ["white"], pattern: "maroon home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/qatar/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Qatar_national_football_team.jpg/500px-Qatar_national_football_team.jpg"], confidence: "low" },
  { teamId: "jordan", team: "Jordan", season: kitSeason, variant: "home", manufacturer: "Hummel", mainSponsor: "none", baseColor: "white", accentColors: ["red", "black", "green"], pattern: "white home shirt with red trim", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/jordan/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Asian_Nations_Cup_-_Jordan_and_South_Korea_%2867%29.jpg/500px-Asian_Nations_Cup_-_Jordan_and_South_Korea_%2867%29.jpg"], confidence: "low" },
  { teamId: "uzbekistan", team: "Uzbekistan", season: kitSeason, variant: "home", manufacturer: "adidas", mainSponsor: "none", baseColor: "white", accentColors: ["blue", "green"], pattern: "white home shirt with blue trim", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/uzbekistan/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Uzbekistan_national_football_team.jpeg/500px-Uzbekistan_national_football_team.jpeg"], confidence: "low" },
  { teamId: "panama", team: "Panama", season: kitSeason, variant: "home", manufacturer: "unknown", mainSponsor: "none", baseColor: "white", accentColors: ["red", "blue"], pattern: "white home shirt with red and blue trim", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/panama/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Partido_Galicia_-_Panam%C3%A1_en_Bala%C3%ADdos_51.jpg/1280px-Partido_Galicia_-_Panam%C3%A1_en_Bala%C3%ADdos_51.jpg"], confidence: "low" },
  { teamId: "curacao", team: "Curaçao", season: kitSeason, variant: "home", manufacturer: "unknown", mainSponsor: "none", baseColor: "blue", accentColors: ["white", "yellow"], pattern: "blue home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/curacao/home.png", sourceUrls: ["https://en.wikipedia.org/wiki/Cura%C3%A7ao_national_football_team"], confidence: "low" },
  { teamId: "haiti", team: "Haiti", season: kitSeason, variant: "home", manufacturer: "unknown", mainSponsor: "none", baseColor: "blue", accentColors: ["red"], pattern: "blue home shirt", collar: "unknown", cuffs: "unknown", crestPlacement: "unknown", sponsorPlacement: "unknown", shorts: "unknown", socks: "unknown", referenceImageUrl: "https://gldtjiofbokiqcordale.supabase.co/storage/v1/object/public/kit-images/international/haiti/home.jpg", sourceUrls: ["https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Bundesarchiv_Bild_183-N0615-0032%2C_Fu%C3%9Fball-WM%2C_Italien_-_Haiti_3-1.jpg/500px-Bundesarchiv_Bild_183-N0615-0032%2C_Fu%C3%9Fball-WM%2C_Italien_-_Haiti_3-1.jpg"], confidence: "low" },
];

export function getKitSpec(teamId: string, variant: KitVariant): KitSpec | undefined {
  const all = [...kitSpecs, ...fallbackKitSpecs, ...internationalKitSpecs];
  // Look for an exact variant match first
  const exact = all.find((spec) => spec.teamId === teamId && spec.variant === variant);
  if (exact) return exact;
  // For retro: fall back to home spec so we surface classic reference images
  if (variant === "retro") {
    return all.find((spec) => spec.teamId === teamId && spec.variant === "home");
  }
  return undefined;
}

export function describeKitSpec(spec: KitSpec, variant?: KitVariant): string {
  const isRetro = variant === "retro";
  return [
    isRetro
      ? `Classic/retro era ${spec.team} kit (use a vintage football shirt aesthetic — worn fabric texture, bold retro badge, no modern sponsor branding)`
      : `${spec.season} ${spec.team} ${spec.variant} kit`,
    `Manufacturer: ${isRetro ? "vintage/unknown" : spec.manufacturer}`,
    `Main sponsor: ${isRetro ? "none (retro era, no chest sponsor)" : spec.mainSponsor}`,
    !isRetro && spec.sleeveSponsor ? `Sleeve sponsor: ${spec.sleeveSponsor}` : undefined,
    `Base color: ${spec.baseColor}`,
    `Accent colors: ${spec.accentColors.join(", ")}`,
    `Pattern: ${spec.pattern}`,
    `Collar: ${spec.collar}`,
    `Cuffs: ${spec.cuffs}`,
    `Crest placement: ${spec.crestPlacement}`,
    `Sponsor placement: ${spec.sponsorPlacement}`,
    `Shorts: ${spec.shorts}`,
    `Socks: ${spec.socks}`
  ].filter(Boolean).join("\n");
}
